# - Find libavformat
# Find the native libavformat includes and library
# This module defines
#  AVFORMAT_INCLUDE_DIRS, where to find avformat.h, etc.
#  AVFORMAT_LIBRARIES, the libraries needed to use libavformat.
#  AVFORMAT_RUNTIME_LIBRARY_PATH - where to find runtime libraries (WIN32)
#  AVFORMAT_FOUND, If false, do not try to use libavformat.

if(WIN32)
	FIND_PATH(DEFAULT_AVFORMAT_INCLUDE_DIR libavformat/avformat.h)
else(WIN32)
	FIND_PATH(DEFAULT_AVFORMAT_INCLUDE_DIR libavformat/avformat.h PATHS /usr/local/include /usr/include)
endif(WIN32)
if(WIN32 AND DEFAULT_AVFORMAT_INCLUDE_DIR)
	set(AVFORMAT_RUNTIME_LIBRARY_PATH ${DEFAULT_AVFORMAT_INCLUDE_DIR}/../bin)
endif(WIN32 AND DEFAULT_AVFORMAT_INCLUDE_DIR)

SET(AVUTIL_NAMES ${AVUTIL_NAMES} avutil)
FIND_LIBRARY(DEFAULT_AVUTIL_LIBRARY
    NAMES ${AVUTIL_NAMES}
    PATHS /usr/lib /usr/local/lib
)
SET(AVFORMAT_NAMES ${AVFORMAT_NAMES} avformat)
FIND_LIBRARY(DEFAULT_AVFORMAT_LIBRARY
    NAMES ${AVFORMAT_NAMES}
    PATHS /usr/lib /usr/local/lib
)

IF (DEFAULT_AVFORMAT_LIBRARY AND DEFAULT_AVFORMAT_INCLUDE_DIR)
    SET(AVFORMAT_INCLUDE_DIRS ${DEFAULT_AVFORMAT_INCLUDE_DIR})
    SET(AVFORMAT_LIBRARIES ${DEFAULT_AVUTIL_LIBRARY} ${DEFAULT_AVFORMAT_LIBRARY})
    SET(AVFORMAT_FOUND TRUE)
ELSE (DEFAULT_AVFORMAT_LIBRARY AND DEFAULT_AVFORMAT_INCLUDE_DIR)
    SET(AVFORMAT_FOUND FALSE)
ENDIF (DEFAULT_AVFORMAT_LIBRARY AND DEFAULT_AVFORMAT_INCLUDE_DIR)

# Get the version
get_filename_component(DEFAULT_AVFORMAT_LIBRARY_REALPATH ${DEFAULT_AVFORMAT_LIBRARY} REALPATH)
string(REGEX REPLACE ".*\\.so\\.(.*)" "\\1" AVFORMAT_VERSION ${DEFAULT_AVFORMAT_LIBRARY_REALPATH})
if(AVFORMAT_VERSION)
    string(REGEX REPLACE "([0-9]+).*" "\\1" AVFORMAT_VERSION_MAJOR ${AVFORMAT_VERSION})
    string(REGEX REPLACE "[0-9]+\\.([0-9]+).*" "\\1" AVFORMAT_VERSION_MINOR ${AVFORMAT_VERSION})
endif(AVFORMAT_VERSION)

IF (AVFORMAT_FOUND)
    IF (NOT AVFORMAT_FIND_QUIETLY)
        MESSAGE(STATUS "Found libavformat: ${AVFORMAT_LIBRARIES}")
    ENDIF (NOT AVFORMAT_FIND_QUIETLY)
ELSE (AVFORMAT_FOUND)
    IF (AVFORMAT_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find libavformat")
     ENDIF (AVFORMAT_FIND_REQUIRED)
ENDIF (AVFORMAT_FOUND)

MARK_AS_ADVANCED(
  AVFORMAT_LIBRARIES
  AVFORMAT_INCLUDE_DIRS
)

