# - Find libswresample
# Find the native libswresample includes and library
# This module defines
#  SWRESAMPLE_INCLUDE_DIRS, where to find swresample.h, etc.
#  SWRESAMPLE_LIBRARIES, the libraries needed to use SWRESAMPLE.
#  SWRESAMPLE_RUNTIME_LIBRARY_PATH - where to find runtime libraries (WIN32)
#  SWRESAMPLE_FOUND, If false, do not try to use SWRESAMPLE.


if(WIN32)
	FIND_PATH(DEFAULT_SWRESAMPLE_INCLUDE_DIR libswresample/swresample.h)
else(WIN32)
	FIND_PATH(DEFAULT_SWRESAMPLE_INCLUDE_DIR libswresample/swresample.h PATHS /usr/local/include /usr/include)
endif(WIN32)
if(WIN32 AND DEFAULT_SWRESAMPLE_INCLUDE_DIR)
	set(SWRESAMPLE_RUNTIME_LIBRARY_PATH ${DEFAULT_SWRESAMPLE_INCLUDE_DIR}/../bin)
endif(WIN32 AND DEFAULT_SWRESAMPLE_INCLUDE_DIR)

SET(SWRESAMPLE_NAMES ${SWRESAMPLE_NAMES} swresample)
FIND_LIBRARY(DEFAULT_SWRESAMPLE_LIBRARY
    NAMES ${SWRESAMPLE_NAMES}
    PATHS /usr/lib /usr/local/lib
)

IF (DEFAULT_SWRESAMPLE_LIBRARY AND DEFAULT_SWRESAMPLE_INCLUDE_DIR)
    SET(SWRESAMPLE_INCLUDE_DIRS ${DEFAULT_SWRESAMPLE_INCLUDE_DIR})
    SET(SWRESAMPLE_LIBRARIES ${DEFAULT_SWRESAMPLE_LIBRARY})
    SET(SWRESAMPLE_FOUND TRUE)
ELSE (DEFAULT_SWRESAMPLE_LIBRARY AND DEFAULT_SWRESAMPLE_INCLUDE_DIR)
    SET(SWRESAMPLE_FOUND FALSE)
ENDIF (DEFAULT_SWRESAMPLE_LIBRARY AND DEFAULT_SWRESAMPLE_INCLUDE_DIR)

# Get the version
get_filename_component(DEFAULT_SWRESAMPLE_LIBRARY_REALPATH ${DEFAULT_SWRESAMPLE_LIBRARY} REALPATH)
string(REGEX REPLACE ".*\\.so\\.(.*)" "\\1" SWRESAMPLE_VERSION ${DEFAULT_SWRESAMPLE_LIBRARY_REALPATH})
if(SWRESAMPLE_VERSION)
    string(REGEX REPLACE "([0-9]+).*" "\\1" SWRESAMPLE_VERSION_MAJOR ${SWRESAMPLE_VERSION})
    string(REGEX REPLACE "[0-9]+\\.([0-9]+).*" "\\1" SWRESAMPLE_VERSION_MINOR ${SWRESAMPLE_VERSION})
endif(SWRESAMPLE_VERSION)

IF (SWRESAMPLE_FOUND)
    IF (NOT SWRESAMPLE_FIND_QUIETLY)
        MESSAGE(STATUS "Found libswresample: ${SWRESAMPLE_LIBRARIES}")
    ENDIF (NOT SWRESAMPLE_FIND_QUIETLY)
ELSE (SWRESAMPLE_FOUND)
    IF (SWRESAMPLE_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find libswresample")
    ENDIF (SWRESAMPLE_FIND_REQUIRED)
ENDIF (SWRESAMPLE_FOUND)

MARK_AS_ADVANCED(
  SWRESAMPLE_LIBRARIES
  SWRESAMPLE_INCLUDE_DIRS
)

